const hotel = [
  {
    id: 1,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 2,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 3,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 4,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 5,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 6,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 7,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 8,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 9,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 10,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 11,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 12,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 13,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 14,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 15,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 16,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 17,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 18,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 19,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 20,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 21,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 22,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 23,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 24,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 25,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 26,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 27,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 28,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 29,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 30,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 31,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 32,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
  {
    id: 33,
    name: "RCE Theaters - 907 S Beckford Dr, Henderson, NC 27536",
    location: "8558 Pecan St",
    rent: "$7225",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "1 Bath",
    size: "732 sft",
    city: "New York",
  },
  {
    id: 34,
    name: "XYZ Apartments - 123 Main St, New York, NY 10001",
    location: "456 Elm St",
    rent: "$6500",
    room: "2 Rooms",
    bed: "3 bed",
    bath: "2 Bath",
    size: "900 sft",
    city: "Mumbai",
  },
  {
    id: 35,
    name: "Elegant Homes - 456 Oak St, Paris, 75001",
    location: "789 Maple St",
    rent: "$8500",
    room: "4 Rooms",
    bed: "5 bed",
    bath: "3 Bath",
    size: "1200 sft",
    city: "Paris",
  },
  {
    id: 36,
    name: "London Residences - 789 Bond St, London, WC1E 6BT",
    location: "1011 Elm St",
    rent: "$9000",
    room: "3 Rooms",
    bed: "4 bed",
    bath: "2 Bath",
    size: "950 sft",
    city: "London",
  },
];
export default hotel;
